<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_pembayaran extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_pembayaran_model');
    } 

    /*
     * Listing of tbl_pembayaran
     */
    function index()
    {
        $data['tbl_pembayaran'] = $this->Tbl_pembayaran_model->get_all_tbl_pembayaran();
        
        $data['_view'] = 'tbl_pembayaran/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_pembayaran
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('total_pembayaran','Total Pembayaran','numeric');
		$this->form_validation->set_rules('jumlah_pembayaran','Jumlah Pembayaran','numeric');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'status' => $this->input->post('status'),
				'id_pesanan' => $this->input->post('id_pesanan'),
				'total_pembayaran' => $this->input->post('total_pembayaran'),
				'jumlah_pembayaran' => $this->input->post('jumlah_pembayaran'),
            );
            
            $tbl_pembayaran_id = $this->Tbl_pembayaran_model->add_tbl_pembayaran($params);
            redirect('tbl_pembayaran/index');
        }
        else
        {            
            $data['_view'] = 'tbl_pembayaran/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_pembayaran
     */
    function edit($id_pembayaran)
    {   
        // check if the tbl_pembayaran exists before trying to edit it
        $data['tbl_pembayaran'] = $this->Tbl_pembayaran_model->get_tbl_pembayaran($id_pembayaran);
        
        if(isset($data['tbl_pembayaran']['id_pembayaran']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('total_pembayaran','Total Pembayaran','numeric');
			$this->form_validation->set_rules('jumlah_pembayaran','Jumlah Pembayaran','numeric');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'status' => $this->input->post('status'),
					'id_pesanan' => $this->input->post('id_pesanan'),
					'total_pembayaran' => $this->input->post('total_pembayaran'),
					'jumlah_pembayaran' => $this->input->post('jumlah_pembayaran'),
                );

                $this->Tbl_pembayaran_model->update_tbl_pembayaran($id_pembayaran,$params);            
                redirect('tbl_pembayaran/index');
            }
            else
            {
                $data['_view'] = 'tbl_pembayaran/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_pembayaran you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_pembayaran
     */
    function remove($id_pembayaran)
    {
        $tbl_pembayaran = $this->Tbl_pembayaran_model->get_tbl_pembayaran($id_pembayaran);

        // check if the tbl_pembayaran exists before trying to delete it
        if(isset($tbl_pembayaran['id_pembayaran']))
        {
            $this->Tbl_pembayaran_model->delete_tbl_pembayaran($id_pembayaran);
            redirect('tbl_pembayaran/index');
        }
        else
            show_error('The tbl_pembayaran you are trying to delete does not exist.');
    }
    
}
